# Generated by Django 4.1.7 on 2023-03-31 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NameModel',
            new_name='Table',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='name',
            new_name='title',
        ),
    ]
