# Generated by Django 4.1.7 on 2023-04-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_rename_namemodel_table_rename_name_table_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table23',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField()),
                ('name_of_partner', models.CharField(max_length=100)),
                ('date_of_contract', models.CharField(max_length=40)),
                ('start_date', models.CharField(max_length=40)),
                ('end_date', models.CharField(max_length=40)),
                ('availability', models.CharField(max_length=100)),
            ],
        ),
    ]
