# Generated by Django 4.1.7 on 2023-04-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_table23'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table26',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=100)),
                ('subject_of_contract', models.CharField(max_length=100)),
                ('directon_of_speciality', models.CharField(max_length=40)),
                ('date', models.CharField(max_length=40)),
                ('terms_of_the_contract', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='table23',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
