# Generated by Django 4.1.7 on 2023-04-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_table26_alter_table23_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table23',
            name='date_of_contract',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='table23',
            name='end_date',
            field=models.IntegerField(max_length=40),
        ),
        migrations.AlterField(
            model_name='table23',
            name='start_date',
            field=models.IntegerField(max_length=40),
        ),
        migrations.AlterField(
            model_name='table26',
            name='date',
            field=models.IntegerField(max_length=40),
        ),
    ]
