# Generated by Django 4.1.7 on 2023-04-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_alter_table23_date_of_contract_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table26',
            name='date',
        ),
        migrations.AddField(
            model_name='table26',
            name='date_of_conclusion_of_the_contract',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='table23',
            name='date_of_contract',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='table23',
            name='end_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='table23',
            name='start_date',
            field=models.CharField(max_length=100),
        ),
    ]
