# Generated by Django 4.1.7 on 2023-04-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_remove_table26_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table23',
            name='start_date',
            field=models.DateField(),
        ),
    ]
