# Generated by Django 4.1.7 on 2023-04-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_alter_table23_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table23',
            name='start_date',
            field=models.CharField(max_length=100),
        ),
    ]
