# Generated by Django 4.1.7 on 2023-04-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0012_alter_table23_date_of_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table26',
            name='date_of_conclusion_of_the_contract',
            field=models.DateField(),
        ),
    ]
