# Generated by Django 4.1.7 on 2023-06-28 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0013_alter_table26_date_of_conclusion_of_the_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
