# Generated by Django 4.1.7 on 2023-06-30 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0014_table_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='table23',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='table26',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
